# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.2
language:
    - swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/PurchaseController.xcworkspace -scheme PurchaseController-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.3,name=iPhone X' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
